name: Git hub continuos integration

on: [pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Code style
        run: npm run lint

      - name: UI E2E Tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          headless: true
